### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by vladyslav-maryniak** [vladyslav-maryniak/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by marik256** [comment]
~~Experience~~ Operations

**Game Over – Altay Mountains, Russia – 2011**

My team, USMC and SAS units were assigned to pursue Imran Zakhayev. We moved in UAZs. When enemy trucks with armed ultranationalists and a Hind helicopter covering them appeared, my group and the other groups split up to effectively destroy the enemy. We had to stop because a bridge had been blown in front of us. We continued to fight waiting for support. During the fight, three of my guys were killed and I and another member of my team were badly wounded by the explosion. While trying to finish us off, Imran Zakhaev and his guards were distracted by an arriving Mi-28 Loyalist Havoc. Taking advantage of this moment, my teammate killed them. We were then evacuated and the operation was completed.

**Ultimatum – Altay Mountains, Russia – 2011**

My crew was ejected with parachutes to the starting point. On landing, one team member was carried off in the other direction. Tracing his signal, we went into the village and pulled the member out. We then proceeded to complete the mission. The team made their way to the electrical tower, which was destroyed with C4. After de-energizing the nuclear facility, the group split up. During the sweep, a few of the team members and I teamed up with a team of American snipers. But during the battle, nuclear missiles were launched. After breaking through a large enemy force, my team began mopping up the control bunker under the cover of Marines. After that, a member of my team entered deactivation codes for the missiles launched.

**The Sins of the Father – Uzlovoy, Krasnodar Krai, Russia – 2011**

My group was ordered to capture Victor Zakhayev alive. Together with Russian loyalists and marines, we captured an enemy roadblock and ambushed it. Upon the arrival of Victor Zakhaev, the ultranationalists were eliminated, but Victor escapes. Members of my group pursued him, making their way through the armed groups of the enemy, but Victor shot himself. The operation was partially failed.

**Heat – Amsar, Azerbaijan – 2011**

I was given the task of holding the evacuation site. Having prepared to defend ourselves, we took the fight. However, the enemy mistook our group for a much larger force and covered us with mortars. After retreating, we had to eliminate four T-72 tanks with a Javelin missile system. Based on the situation, we made our way back to our previous position. Everyone successfully evacuated except Mac, who died providing fire support to the squad.

**Safehouse – Amsar, Azerbaijan – 2011**

My team was involved in the capture of Khaled al-Asad in his safe house. With the support of a member of the Russian loyalist squad and a helicopter, we liquified the ultranationalists who were guarding Al-Assad. During the interrogation, I found out that the bomb had been handed over by Imran Zakhaev and that Al-Asad had subsequently been liquidated.

**Hunted – Arkhangelsk Oblast, Russia – 2011**

On the way to Germany's safehouse to deposit Nikolai, our helicopter was shot down. As a result of the crash, some crew members die. We had to make our way to the evacuation point, encountering enemy armed groups. All the while, we were escorted by an enemy helicopter, which was destroyed by a crew member, Soap, with a Stinger missile. An AC-130 came to support us. After a hard fight with the enemy we were evacuated and taken to our destination.

**Blackout – Caucasus Mountains, Russia – 2011**

I participated in a rescue mission into the Caucasus to retrieve the informant Nikolai, who was supplying the SAS with intelligence. He had been taken prisoner by the rebel forces. We acted together with Russian loyalists led by Sergeant Kamarov. My team provided sniper support from a nearby ridge and eliminates a force of Ultranationalist helicopter troops. After destroying most of the enemy force, we fought our way to Nikolai and, after completely clearing the village, evacuated.

**Crew Expendable – Bering Strait – 2011**

I led the SAS team to the Estonian freighter Väljakutse in the Bering Strait. Our target was to find a suspected nuclear device hidden in a box in one of the ship's cargo compartments. During the operation, we found the package, which turned out to be plutonium and a cargo manifest indicating the alleged buyer - Middle Eastern coup leader Khaled Al-Asad. The raid was a partial success, although we could not secure the nuclear device for safekeeping;

**Captive – Tobrak, Urzikstan – 2009**

Commanding Bravo unit, I was informed about the Russian chemical laboratory in Urzikstan by commander Karim of the Urzikstan Liberation Force; acting on this, the SAS launched a raid on the facility, and I helped commander Farah Karim. In helping her, my crew saved a group of prisoners in the lab, including Farah's brother, Khadir.

**One Shot, One Kill – Pripyat, Ukraine – 1996**

When I was still a lieutenant, I was involved in an assassination attempt on ultranationalist politician Imran Zakhayev under the command of then Captain McMillan in Pripyat, Ukraine. The assassination attempt was unsuccessful.

**Comment by vladyslav-maryniak** [comment]
LGTM!

**Comment by marik256** [comment]
### ~~Experience~~ Operations
```html
<h3><s>Experience</s> Operations</h3>
<ul class="timeline">
  <li>
    <p><strong>Game Over – Altay Mountains, Russia – 2011</strong></p>
    <p>My team, USMC and SAS units were assigned to pursue Imran Zakhayev. We moved in UAZs. When enemy
      trucks with armed ultranationalists and a Hind helicopter covering them appeared, my group and the
      other groups split up to effectively destroy the enemy. We had to stop because a bridge had been
      blown in front of us. We continued to fight waiting for support. During the fight, three of my guys
      were killed and I and another member of my team were badly wounded by the explosion. While trying to
      finish us off, Imran Zakhaev and his guards were distracted by an arriving Mi-28 Loyalist Havoc.
      Taking advantage of this moment, my teammate killed them. We were then evacuated and the operation
      was completed.</p>
  </li>
  <li>
    <p><strong>Ultimatum – Altay Mountains, Russia – 2011</strong></p>
    <p>My crew was ejected with parachutes to the starting point. On landing, one team member was carried
      off in the other direction. Tracing his signal, we went into the village and pulled the member out.
      We then proceeded to complete the mission. The team made their way to the electrical tower, which
      was destroyed with C4. After de-energizing the nuclear facility, the group split up. During the
      sweep, a few of the team members and I teamed up with a team of American snipers. But during the
      battle, nuclear missiles were launched. After breaking through a large enemy force, my team began
      mopping up the control bunker under the cover of Marines. After that, a member of my team entered
      deactivation codes for the missiles launched.</p>
  </li>
  <li>
    <p><strong>The Sins of the Father – Uzlovoy, Krasnodar Krai, Russia – 2011</strong></p>
    <p>My group was ordered to capture Victor Zakhayev alive. Together with Russian loyalists and marines,
      we captured an enemy roadblock and ambushed it. Upon the arrival of Victor Zakhaev, the
      ultranationalists were eliminated, but Victor escapes. Members of my group pursued him, making their
      way through the armed groups of the enemy, but Victor shot himself. The operation was partially
      failed.</p>
  </li>
  <li>
    <p><strong>Heat – Amsar, Azerbaijan – 2011</strong></p>
    <p>I was given the task of holding the evacuation site. Having prepared to defend ourselves, we took
      the fight. However, the enemy mistook our group for a much larger force and covered us with mortars.
      After retreating, we had to eliminate four T-72 tanks with a Javelin missile system. Based on the
      situation, we made our way back to our previous position. Everyone successfully evacuated except
      Mac, who died providing fire support to the squad.</p>
  </li>
  <li>
    <p><strong>Safehouse – Amsar, Azerbaijan – 2011</strong></p>
    <p>My team was involved in the capture of Khaled al-Asad in his safe house. With the support of a
      member of the Russian loyalist squad and a helicopter, we liquified the ultranationalists who were
      guarding Al-Assad. During the interrogation, I found out that the bomb had been handed over by Imran
      Zakhaev and that Al-Asad had subsequently been liquidated.</p>
  </li>
  <li>
    <p><strong>Hunted – Arkhangelsk Oblast, Russia – 2011</strong></p>
    <p>On the way to Germany's safehouse to deposit Nikolai, our helicopter was shot down. As a result of
      the crash, some crew members die. We had to make our way to the evacuation point, encountering enemy
      armed groups. All the while, we were escorted by an enemy helicopter, which was destroyed by a crew
      member, Soap, with a Stinger missile. An AC-130 came to support us. After a hard fight with the
      enemy we were evacuated and taken to our destination.</p>
  </li>
  <li>
    <p><strong>Blackout – Caucasus Mountains, Russia – 2011</strong></p>
    <p>I participated in a rescue mission into the Caucasus to retrieve the informant Nikolai, who was
      supplying the SAS with intelligence. He had been taken prisoner by the rebel forces. We acted
      together with Russian loyalists led by Sergeant Kamarov. My team provided sniper support from a
      nearby ridge and eliminates a force of Ultranationalist helicopter troops. After destroying most of
      the enemy force, we fought our way to Nikolai and, after completely clearing the village, evacuated.
    </p>
  </li>
  <li>
    <p><strong>Crew Expendable – Bering Strait – 2011</strong></p>
    <p>I led the SAS team to the Estonian freighter Väljakutse in the Bering Strait. Our target was to
      find a suspected nuclear device hidden in a box in one of the ship's cargo compartments. During the
      operation, we found the package, which turned out to be plutonium and a cargo manifest indicating
      the alleged buyer - Middle Eastern coup leader Khaled Al-Asad. The raid was a partial success,
      although we could not secure the nuclear device for safekeeping;</p>
  </li>
  <li>
    <p><strong>Captive – Tobrak, Urzikstan – 2009</strong></p>
    <p>Commanding Bravo unit, I was informed about the Russian chemical laboratory in Urzikstan by
      commander Karim of the Urzikstan Liberation Force; acting on this, the SAS launched a raid on the
      facility, and I helped commander Farah Karim. In helping her, my crew saved a group of prisoners in
      the lab, including Farah's brother, Khadir.</p>
  </li>
  <li>
    <p><strong>One Shot, One Kill – Pripyat, Ukraine – 1996</strong></p>
    <p>When I was still a lieutenant, I was involved in an assassination attempt on ultranationalist
      politician Imran Zakhayev under the command of then Captain McMillan in Pripyat, Ukraine. The
      assassination attempt was unsuccessful.</p>
  </li>
</ul>
```
